### ISSUE TITLE
User Story: Viewing Products

### ISSUE THREAD

**Issue by leec313** [leec313/Fetch-and-Feast#14]
### Child of:

- #13 

As a **user** I can **see and interact with a list of products available on the site**

# Acceptance Criteria

- Comprehensive product listing is available
- The product list precisely corresponds to the product database objects
- Users can click on products to access detailed information
- Products can be conveniently added to the user's basket

# Tasks

- [x]  Establish a view and URL for the product list
- [x]  Link the view to the product model
- [x]  Create a view and URL for the product detail view
- [x]  Develop HTML templates for both the product list and product detail pages
