### ISSUE TITLE
User Story: Product Search, Filter & Sort

### ISSUE THREAD

**Issue by leec313** [leec313/Fetch-and-Feast#16]
### Child of:

- #13 

As a **user** I can **search for and sort products** so that **I can easily find the most suitable product for my needs**

# Acceptance Criteria

- User can search for products
- Search returns relevant products
- User is informed if search returns nothing
- Products can be sorted by their attributes including name, category, date-added, price
- User can filter products by a particular set of parameters

# Tasks

- [x]  Add HTML & CSS for search box
- [x]  Create HTML search form and return searches to view
- [x]  Create search & filter functionality in view using Q module
- [x]  Add sorting links to products page
- [x]  Add sorting, filtering & ordering functionality to product view
