### ISSUE TITLE
User Story: Add Product to Shopping Bag

### ISSUE THREAD

**Issue by leec313** [leec313/Fetch-and-Feast#19]
### Child of:

- #18

As a **user** I can **add products to my shopping basket** so that **I can pre-select them for possible purchase**

# Acceptance Criteria

- Add to bag button appears for every product
- Buttons add correct product to bag
- Basket running costs are updated correctly

# Tasks

- [x]  Add HTML for add to bag button
- [x]  Add logic for adding selected product to basket
- [x] Add logic and template code for updating product quantities from bag page
