### ISSUE TITLE
User Story: Product Pricing

### ISSUE THREAD

**Issue by leec313** [leec313/Fetch-and-Feast#23]
### Child of:

- #22

As a **user** I can **see prices of all products** so that **I have an accurate measure of the costs of all products that I view**

# Acceptance Criteria

- Accurate prices displayed on all products
- Prices are uniform across users' basket and at checkout
- Prices are correctly summed to give user a total cost at checkout

# Tasks

- [x]  Add HTML for product price display
- [x]  Set price field in product's entry in Product Model
- [x]  Create logic for summing product costs and shipping
