### ISSUE TITLE
User Story: Payments

### ISSUE THREAD

**Issue by leec313** [leec313/Fetch-and-Feast#24]
### Child of:

- #22 

As a **user** I can **use my credit/debit card to pay for products** so that **I can use the online payment system on the site and receive my products as expected with an ecommerce site**.

# Acceptance Criteria

- Front-end form allows users to enter their card details
- Card details are checked for validation, and user is informed if they entered details incorrectly
- Card details are kept secure throughout the payment process
- Extra validation prompts, such as card issuer validation prompts, appear if necessary.

# Tasks

- [x]  Link site with Stripe
- [x]  Import Stripe card payment form into HTML
- [x]  Test Stripe payments
