### ISSUE TITLE
User Story: Order Numbers

### ISSUE THREAD

**Issue by leec313** [leec313/Fetch-and-Feast#25]
### Child of:

- #22   

As an **admin** I can **create orders & order numbers for user purchases** so that **orders can be organised & stored correctly, and reviewed if need be**

Also As **user** I can **receive order numbers after my purchases** so that **I can track my orders using the unique confirmation number**.

# Acceptance Criteria

- Order numbers are created upon user purchase
- Order numbers are linked correctly with orders and stored in the database
- User can see their order number after purchase

# Tasks

- [x]  Create Order model with unique order numbers
- [x]  Add logic to create an Order object upon user order
- [x]  Insert order number into order confirmation HTML
