### ISSUE TITLE
User Story: Webhooks for Secure Payment Process

### ISSUE THREAD

**Issue by leec313** [leec313/Fetch-and-Feast#26]
### Child of:

- #22 

As an **admin**, I can **initiate a secure sequence of payment processes** so that **users cannot inadvertently or deliberately disrupt the processing of their payment or the creation of their order once it has commenced.**

# Acceptance Criteria

- User input does not interrupt payment processing and order creation
- Webhooks establish a secure sequence of events
- Database operations are handled accurately, even if the user closes or refreshes the page during payment processing
- Users receive correct order completion with an order number and email notification

# Tasks

- [x]  Create webhooks.py & webhook handler.py
- [x]  Import stripe code
- [x]  Add code for webhook handlers
- [x]  Test webhooks in stripe
