### ISSUE TITLE
User Story: Confirmation Emails after Purchase

### ISSUE THREAD

**Issue by leec313** [leec313/Fetch-and-Feast#27]
### Child of:

- #22   

As a **user** I can **receive purchase confirmation emails** so that **I have confirmation of my order, and a record of my purchase and important order information**

# Acceptance Criteria

- Emails are sent to user's email upon purchase
- Emails contain list of items purchased and price paid
- Emails contain the purchase's unique order number

# Tasks

- [x]  Create default email content
- [x]  Add order number to email
- [x]  Add order items to email
