### ISSUE TITLE
User Story: Newsletter Emails

### ISSUE THREAD

**Issue by leec313** [leec313/Fetch-and-Feast#36]
### Child of:

- #33
-
As an **admin** I can **send the site newsletter to signed-up users** so that **I can inform them of news and updates about the site**

# Acceptance Criteria

- Site newsletter can be sent to all email addresses in newsletter database model
- Newsletter is created from an email template and is editable on site frontend
- Newsletter email contains site links, as well as link to unsubscribe

# Tasks

- [ ]  Create sendmail functionality in views
- [ ]  Create email template for newsletter
- [x]  Add links to newsletter email for users to unsubscribe

**Comment by leec313** [comment]
Moving this back into to- do column (mistakenly added to done) and adding won't have tag. 

I would have really like to add this but it's not something I have time for.
