### ISSUE TITLE
User Story: Blog Database and CRUD

### ISSUE THREAD

**Issue by leec313** [leec313/Fetch-and-Feast#38]
### Child of:

- #37

As an **admin** I can **create, read, update and delete content for the blog from the backend model/database** so that **I can fully manage the blog app on the site**

# Acceptance Criteria

- Blog model exists in site backend with relevant fields
- Views, URLs, forms and Templates exist and are linked up correctly
- Allow users to comment on and like posts

# Tasks

- [x]  Create database model
- [x]  Link model to templates, views and forms
- [x] Ensure full CRUD functionality is present
