### ISSUE TITLE
User Story: Ratings Model, Views & Templates

### ISSUE THREAD

**Issue by leec313** [leec313/Fetch-and-Feast#45]
### Child of:

- #44 

As an **admin** I can **see the product ratings on the product pages and backend** so that **I can manage ratings accordingly**

# Acceptance Criteria

- User can see product ratings
- Users without an account can see but not submit a rating
- Users with an account can submit a rating if they have purchased the product

# Tasks

- [x]  Add Ratings model
- [x]  Add the view/update existing view
- [x] Add code to templates so that users can view/create the ratings
- [x] Ensure only users who have purchased the product can submit a rating
