### ISSUE TITLE
User Story: User Profiles

### ISSUE THREAD

**Issue by leec313** [leec313/Fetch-and-Feast#7]
### Child of:

#1 

As a **user** I can **see and edit my personal user profile** so that **I can see my saved user details and other information such as past orders**

### Acceptance Criteria

- Profiles are created automatically upon user registration
- Profiles display users' relevant information
- Profile details are editable by user
- Users may only edit their own profile and cannot see other users' sensitive information

### Tasks

- [x]  Create HTML for user profiles
- [x]  Create Profile model
- [x]  Create Django signal for automatic profile creation on register
- [x]  Create Profile form for user editing & link it to profile model
